Repository google-deepmind/open_spiel, pull requests merged in 2024-08, with the labels that each got.

#1255 Improve Windows compatibility
  docs/windows.md
  open_spiel/games/bridge/bridge.cc
  open_spiel/games/twixt/twixtboard.cc
  open_spiel/utils/file.cc
Labels: imported, Windows, merged internally

#1258 Remove include of smart_holder_type_casters.h header
  open_spiel/python/pybind11/games_dots_and_boxes.cc
  open_spiel/python/pybind11/pybind11.h
Labels: imported

#1259 Fix DQN bug (wrong target Q-value for illegal actions)
  open_spiel/python/pytorch/dqn.py
Labels: imported, merged internally

#1264 Open Spiel Visual Graph
  docs/contributing.md
Labels: imported, merged internally

#1267 Fix for issue #1266
  open_spiel/python/algorithms/efr.py
Labels: imported, merged internally

#1265 Fix RCFR test and example to work with Keras 3
  open_spiel/python/CMakeLists.txt
  open_spiel/python/algorithms/rcfr_test.py
  open_spiel/python/examples/rcfr_example.py
Labels: imported, merged internally

#1271 Fixed NumPy deprication warning in efr.py
  open_spiel/python/algorithms/efr.py
Labels: imported, merged internally

#1275 Fix: phantom tic-tac-toe and dark hex information state when obs type is reveal nothing
  open_spiel/games/dark_hex/dark_hex.cc
  open_spiel/games/dark_hex/dark_hex.h
  open_spiel/games/phantom_ttt/phantom_ttt.cc
  open_spiel/games/phantom_ttt/phantom_ttt.h
  open_spiel/integration_tests/playthroughs/dark_hex(num_rows=5,num_cols=3).txt
  open_spiel/integration_tests/playthroughs/dark_hex_ir(board_size=3).txt
  open_spiel/integration_tests/playthroughs/phantom_ttt.txt
Labels: imported, merged internally
